### ISSUE TITLE
Image problem

### ISSUE THREAD

**Issue by Shreeshan252** [SulashManandhar/Herald-Content-Management#13]
When the image is added by admin. Thumbnail Image wont be added to Watch us page.

**Comment by SulashManandhar** [comment]
This image is about: user adding an image to backend
![image](https://user-images.githubusercontent.com/82258021/118369432-10cc3280-b5c3-11eb-8dba-e10aae7de463.png)
This below image refer to data added to json file
![image](https://user-images.githubusercontent.com/82258021/118369471-3a855980-b5c3-11eb-844b-84e27fb00681.png)
