### ISSUE TITLE
Problem in add event section

### ISSUE THREAD

**Issue by Shreeshan252** [SulashManandhar/Herald-Content-Management#16]
Problem in uploading document in add event section. the document does not upload.

**Comment by Pravesh38** [comment]
ok ill try to solve it as fast as possible

**Comment by Pravesh38** [comment]
I have solved the bug @Shreeshan252  you assigned to me. 
Now, The documents wont have problem in uploading
![upload](https://user-images.githubusercontent.com/82258028/118365557-f98a4680-b5bc-11eb-989e-1dde98d7a15e.jpg)

**Comment by Pravesh38** [comment]
I have solved the bug @Shreeshan252 you assigned to me.
Now, The documents wont have problem in uploading
![upload](https://user-images.githubusercontent.com/82258028/118365717-be3c4780-b5bd-11eb-9609-67ca366e066a.jpg)
