### ISSUE TITLE
Event could not be deleted.

### ISSUE THREAD

**Issue by Shreeshan252** [SulashManandhar/Herald-Content-Management#23]
In event and article page event could not be deleted.

**Comment by Pravesh38** [comment]
Small bug was seen in event page. It is solved now
![delete](https://user-images.githubusercontent.com/82258028/118365416-736e0000-b5bc-11eb-8725-94f6b1501957.jpg)

**Comment by Pravesh38** [comment]
Small bug was seen in event section which is solved now.
![delete](https://user-images.githubusercontent.com/82258028/118365485-add79d00-b5bc-11eb-8a6f-957f05222313.jpg)
